language: groovy
jdk:
  - oraclejdk8

notifications:
  email: false

before_install:
  - cd ./build-whisperer-core/lib/ 
  - sh install.sh
  - cd ../..
after_success:
  - bash <(curl -s https://codecov.io/bash)
